### ISSUE TITLE
infolog.log does not exist

### ISSUE THREAD

**Issue by YannDub** [TeamUbercube/ubercube#2]
infolog.log should be created when the file does not exist. Because for the moment we have this behavior : 

``` java
====== Loading Display... ======
/home/dubois/Ubercube/infolog.log (Aucun fichier ou dossier de ce type)
Exception in thread "main" java.lang.NullPointerException
    at fr.veridiangames.core.utils.Log.addLine(Log.java:81)
    at fr.veridiangames.core.utils.Log.println(Log.java:100)
    at fr.veridiangames.client.rendering.Display.init(Display.java:70)
    at fr.veridiangames.client.rendering.Display.<init>(Display.java:65)
    at fr.veridiangames.client.MainComponent.main(MainComponent.java:36)
```

Maybe it's because I am on Linux ?

**Comment by Marccspro** [comment]
The game is still in development and I haven't had the time to do this. It will come in the future

**Comment by jb-perrier** [comment]
I will implement this feature on next weekend.

This issue is not relative to user's OS.

**Comment by Marccspro** [comment]
Issue fixed
