### ISSUE TITLE
macOS Platform Compatibility

### ISSUE THREAD

**Issue by rocammo** [TeamUbercube/ubercube#7]
I couldn't find the file 'log.txt' you mentioned. I followed the path to ~/Library/Application Support/.ubercube/launcher, but there is no file, not even hidden. The 'data/macos' folder you tell me doesn't exist. Opening 'uberstrap.jar' doesn't crash, it only opens and closes, so it doesn't generate any error reports like 'hs_err_pid*.log'.
Last, I have tried to open it from the terminal to see the execution and it shows the following:

```
Local  version : null
Online version : 1.0
Should download from : https://ubercube.github.io/download/launcher/mac.zip to /Users/rocammo/Library/Application Support/.ubercube/launcher
https://ubercube.github.io/download/launcher/mac.zip
FileType : text/html; charset=utf-8
java.io.FileNotFoundException: https://ubercube.github.io/download/launcher/mac.zip
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at fr.veridiangames.uberstrap.utils.DownloadUtils$1.run(DownloadUtils.java:48)
Caused by: java.io.FileNotFoundException: https://ubercube.github.io/download/launcher/mac.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
	at java.net.URLConnection.getContentType(URLConnection.java:512)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentType(HttpsURLConnectionImpl.java:406)
	at fr.veridiangames.uberstrap.utils.DownloadUtils$1.run(DownloadUtils.java:36)
Exception in thread "Thread-0" java.lang.NullPointerException
	at fr.veridiangames.uberstrap.utils.DownloadUtils$1.run(DownloadUtils.java:80)
java.io.FileNotFoundException: /Users/rocammo/Library/Application Support/.ubercube/launcher/launcherarchive.zip.temp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at fr.veridiangames.uberstrap.utils.ZipUtils.unzip(ZipUtils.java:20)
	at fr.veridiangames.uberstrap.LauncherData.downloadAndUpdate(LauncherData.java:46)
	at fr.veridiangames.uberstrap.UberStrap.update(UberStrap.java:72)
	at fr.veridiangames.uberstrap.UberStrap.main(UberStrap.java:34)
Executing launcher : /Users/rocammo/Library/Application Support/.ubercube/launcher/ubercube_launcher.jar
```

As you can see, the site configured at "https://ubercube.github.io/download/launcher/mac.zip" doesn't contain the requested file.
I hope I've helped you. Regards, Rodrigo.

**Comment by mploux** [comment]
Hi, thanks a lot for the issue, I couldn't test the mac version of the game so I wasn't sure if it worked. I fixed the problem now, so the game should download correctly.
Thanks for the help and have a nice day.

**Comment by rocammo** [comment]
Hi there!
Now you can download the game perfectly and the folder 'data/macos' is created. However, the only thing that can be tested of the game is what I show you in the images below. You cannot play the game. I have tried to join the public server, and also, to open on one side the server and on the other the client, but neither has worked.

<img width="800" alt="uberstrap-launcher" src="https://user-images.githubusercontent.com/9489977/30231826-12e629cc-94ed-11e7-9fa4-8c52d1f0ece0.png">
<img width="308" alt="uberstrap-config" src="https://user-images.githubusercontent.com/9489977/30231830-18e9f34e-94ed-11e7-8285-392c96fd1a98.png">
<img width="600" alt="uberstrap-server" src="https://user-images.githubusercontent.com/9489977/30231833-1bc5df06-94ed-11e7-90c4-30240c3903ba.png">

The closest I've been able to run the client and play the game has been doing the following:
1. Go to `~/Library/Application Support/.ubercube/data/macos`.
2. Open a terminal there.
3. Run the command (to see the execution): `java -cp ubercube.jar fr.veridiangames.client.MainComponent 127.0.0.1:4242 username`

And the result is:
```
Starting Ubercube Pre-Alpha 1.1 v279
glfwInit...
glfwCreateWindow...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1517)
	at fr.veridiangames.client.rendering.Display.init(Display.java:84)
	at fr.veridiangames.client.rendering.Display.<init>(Display.java:69)
	at fr.veridiangames.client.MainComponent.main(MainComponent.java:44)
Caused by: java.lang.IllegalStateException: GLFW windows may only be created on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. For offscreen rendering, make sure another window toolkit (e.g. AWT or JavaFX) is initialized before GLFW.
	at org.lwjgl.glfw.EventLoop$OffScreen.<clinit>(EventLoop.java:37)
	... 4 more
AL lib: (EE) alc_cleanup: 1 device not closed
```

And that's it for now. I hope this information proves to be helpful and give you a clue of the problem. Regards, Rodrigo.

**Comment by mploux** [comment]
Hi, thanks a lot for the help, it's very useful !
There seems to be a problem with glfw with the mac version. I'm going to try to fix the problem and I'll get back here with the solution. I'm reopening the issue in the meantime.
Have a nice day.

**Comment by rocammo** [comment]
[Update]
I have executed the command again with the -XstartOnFirstThread argument:
`$ java -XstartOnFirstThread  -cp ubercube.jar fr.veridiangames.client.MainComponent 127.0.0.1:4242 username`

╘══>
```
Starting Ubercube Pre-Alpha 1.1 v279
glfwInit...
glfwCreateWindow...
glfwSetWindowPos...
glfw inputs callbacks...
glfwMakeContextCurrent...
glfwSwapInterval...
GL.createCapabilities()...
Available GL Version 2.1
Not GL33 compatible !
TCP: Connecting
TCP: Connected !
TCP: Starting tcp-receiver
UDP: Connected !
UDP: Starting udp-receiver
Your trying to connect with id: 576205919
You just connected as username with id: 576205919
Generating world with seed: 684449386
Receiving Red team spawn: 50.0 50.0 50.0
Receiving Blue team spawn: 190.0 50.0 190.0
AL lib: (EE) alc_cleanup: 1 device not closed
```
<img width="1280" alt="ubercube-blackscreen" src="https://user-images.githubusercontent.com/9489977/30233248-8d1a39a2-94f4-11e7-8a5c-a30604fea2a4.png">

I also think it's a problem with glfw with the mac version.
If it works for you, I was also testing the LWJGL 3 library for a while and I had to go back to the previous version (2.9.3) for the same reason, because in macOS the black screen occurred to me when I was implementing the texture class. On Windows, it ran perfectly.

**Comment by mploux** [comment]
Hi, I will push a fix in the launcher to execute the game with the flag for mac users. For the other problem I just pushed, hopefully, a fix on master. Tell me if it helps in any ways.
